// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdnPIlxwhy201-SMUwADnVE4YneqcJ-e8',
    appId: '1:7135146275:web:21edfcefba1402cf8adc96',
    messagingSenderId: '7135146275',
    projectId: 'holi-10c28',
    authDomain: 'holi-10c28.firebaseapp.com',
    storageBucket: 'holi-10c28.firebasestorage.app',
    measurementId: 'G-22HP2BCR49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjI9UD3kDNc0mWdZDsASXCaZIQ4isLqQ',
    appId: '1:7135146275:android:2df16f505a39cb328adc96',
    messagingSenderId: '7135146275',
    projectId: 'holi-10c28',
    storageBucket: 'holi-10c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWU1fqytFFYNltienuUSj9kkkdzD12Rsw',
    appId: '1:7135146275:ios:f2587176f06612508adc96',
    messagingSenderId: '7135146275',
    projectId: 'holi-10c28',
    storageBucket: 'holi-10c28.firebasestorage.app',
    iosBundleId: 'com.example.holi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWU1fqytFFYNltienuUSj9kkkdzD12Rsw',
    appId: '1:7135146275:ios:f2587176f06612508adc96',
    messagingSenderId: '7135146275',
    projectId: 'holi-10c28',
    storageBucket: 'holi-10c28.firebasestorage.app',
    iosBundleId: 'com.example.holi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdnPIlxwhy201-SMUwADnVE4YneqcJ-e8',
    appId: '1:7135146275:web:1a7e177dcf582fb38adc96',
    messagingSenderId: '7135146275',
    projectId: 'holi-10c28',
    authDomain: 'holi-10c28.firebaseapp.com',
    storageBucket: 'holi-10c28.firebasestorage.app',
    measurementId: 'G-665SQFT06J',
  );
}
