// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuxb74IVIa8fxmfKEe63PtfYd5TejFns4',
    appId: '1:277686504554:web:0857ecb939bdd421070e13',
    messagingSenderId: '277686504554',
    projectId: 'heim-1af5d',
    authDomain: 'heim-1af5d.firebaseapp.com',
    storageBucket: 'heim-1af5d.firebasestorage.app',
    measurementId: 'G-CJR4Q607L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NFlsxRlKgGjDRfCAPNr2Xl5umWzHnoQ',
    appId: '1:277686504554:android:640c7700de109f11070e13',
    messagingSenderId: '277686504554',
    projectId: 'heim-1af5d',
    storageBucket: 'heim-1af5d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj-8CKIaRO63YHa5QvMjpztRRL9B9NAs8',
    appId: '1:277686504554:ios:382ffdcff0978a58070e13',
    messagingSenderId: '277686504554',
    projectId: 'heim-1af5d',
    storageBucket: 'heim-1af5d.firebasestorage.app',
    iosBundleId: 'com.example.holi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj-8CKIaRO63YHa5QvMjpztRRL9B9NAs8',
    appId: '1:277686504554:ios:382ffdcff0978a58070e13',
    messagingSenderId: '277686504554',
    projectId: 'heim-1af5d',
    storageBucket: 'heim-1af5d.firebasestorage.app',
    iosBundleId: 'com.example.holi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuxb74IVIa8fxmfKEe63PtfYd5TejFns4',
    appId: '1:277686504554:web:e5ac5e4c8e42f41f070e13',
    messagingSenderId: '277686504554',
    projectId: 'heim-1af5d',
    authDomain: 'heim-1af5d.firebaseapp.com',
    storageBucket: 'heim-1af5d.firebasestorage.app',
    measurementId: 'G-L45PP8X2X7',
  );
}
